### ISSUE TITLE
Train_resF0 Script Error (Dev2)

### ISSUE THREAD

**Issue by usasho** [r9y9/nnsvs#103]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.3-py3.8.egg/nnsvs/bin/train_resf0.py", line 374, in my_app
    last_dev_loss = train_loop(
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.3-py3.8.egg/nnsvs/bin/train_resf0.py", line 269, in train_loop
    loss, log_metrics = train_step(
  File "/usr/local/lib/python3.8/dist-packages/nnsvs-0.0.3-py3.8.egg/nnsvs/bin/train_resf0.py", line 87, in train_step
    pred_out_feats.masked_select(mask), out_feats.masked_select(mask)
AttributeError: 'list' object has no attribute 'masked_select'

What is this error?

**Comment by r9y9** [comment]
I won't be responding until you give us sufficient details. Also, it is highly encouraged to use the master branch (but you seem to use dev branch) unless you are willing to fix any problems on your own.
