### ISSUE TITLE
Error when training PJS database and a custom database

### ISSUE THREAD

**Issue by justln1113** [r9y9/nnsvs#11]
I'm training on Google colab.
I tried to train PJS database with [this config and database](https://github.com/justln1113/TEST/tree/master/PJS)
When I using run.sh include in nnsvs/egs/pjs to train, I got this
```
stage 0: Data preparation
[ERR] Cannot open phoneme table file : /usr/local/lib/sinsy/dic/japanese.utf_8.table
[ERR] Cannot read phoneme table file : /usr/local/lib/sinsy/dic/japanese.utf_8.table
[ERR] Cannot read Japanese table or config or macron file : /usr/local/lib/sinsy/dic/japanese.utf_8.table, /usr/local/lib/sinsy/dic/japanese.utf_8.conf
Traceback (most recent call last):
  File "utils/data_prep.py", line 66, in <module>
    assert sinsy.setLanguages("j", "/usr/local/lib/sinsy/dic")
AssertionError
```

And if I use dic include in [natsume recipe](https://github.com/taroushirani/nnsvs_natsume_singing/tree/master/00-svs-world/dic), I got this
```
stage 0: Data preparation
[WARN] Cannot open macron table file : /content/nnsvs/egs/pjs/00-svs-world/dic/japanese.macron
[WARN] Cannot open macron table file : /content/nnsvs/egs/pjs/00-svs-world/dic/japanese.macron
[WARN] Cannot open macron table file : /content/nnsvs/egs/pjs/00-svs-world/dic/japanese.macron
Traceback (most recent call last):
  File "utils/data_prep.py", line 82, in <module>
    assert len(align_mono_lab) == len(sinsy_mono_lab)
AssertionError
```
And if I use [run.sh](https://github.com/taroushirani/nnsvs_natsume_singing/blob/master/00-svs-world/run.sh) in natsume recipe, I got this(ignore "The last note is not rest")
```
stage 0: Data preparation
[WARN] Duration of notes in a measure is too long
[WARN] Number of notes in a measure is too large
[WARN] Duration of notes in a measure is too long
[WARN] Lyric in unknown language :  in measure 3
[WARN] Lyric in unknown language :  in measure 3
[WARN] Number of notes in a measure is too large
[WARN] Number of notes in a measure is too large
pjs001.lab 0.0
end_time 648800000000000 of the phoneme u and start_time 603700000000000 of the phoneme w is not the same. There seems to be a missing phoneme in sinsy_mono_round.
Traceback (most recent call last):
  File "/content/gdrive/Training_data/PJS/pjs/00-svs-world/utils/align_lab.py", line 41, in <module>
    lab_sinsy = fix_mono_lab_after_align(lab_sinsy)
  File "/content/drive/Shared drives/台U/NNSVS/Training_data/PJS/pjs/00-svs-world/utils/util.py", line 256, in fix_mono_lab_after_align
    f.append((f.end_times[-1], lab.end_times[i], lab.contexts[i]))
  File "/usr/local/lib/python3.6/dist-packages/nnmnkwii/io/hts.py", line 161, in append
    end_time, start_time))
ValueError: end_time (648800000000000) must be larger than start_time (648800000000000).
Traceback (most recent call last):
  File "/content/gdrive/Training_data/PJS/pjs/00-svs-world/utils/perf_segmentation.py", line 71, in <module>
    k, np.min(v), np.max(v), np.mean(v)))
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
Prepare data for time-lag models
  0% 0/1 [00:00<?, ?it/s]pjs001: Global offset (in sec): 91114357.91
  0% 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/content/gdrive/Training_data/PJS/pjs/00-svs-world/utils/finalize_lab.py", line 79, in <module>
    assert seg_idx > 0 or exists(lab_align_path)
AssertionError
```
And I think this is a bug because it also told me `end_time of the phoneme e and start_time of the phoneme u is not the same.` when I was training my custom small database, but I check the lab files, it doesn't exist any e and u connect. By the way, I use `! cd $RECIPE_ROOT && rm -r data/` before training to make sure it will force rewrite.

Then I delete the file randomly in my custom database, it pass that error but it seems like getting a new error.
[console log on pastebin](https://pastebin.com/YGwz0q01)
[my database](https://github.com/justln1113/TEST/tree/master/Kogare)
Sorry, this report is very long and unreadable, so if you have any problem, please tell me. I'm sorry.

**Comment by taroushirani** [comment]
Hello, justln1113.

In the original recipe of PJS corpus, the location of Sinsy dictionary is hard-coded in egs/pjs/00-svs-world/utils/data_prep.py, and the the first error message says there is no sinsy dictionary file under /usr/local/lib/sinsy.  If you built Sinsy with --prefix=/usr (or other place), this may be solved by symbolic link from /usr/lib/sinsy/dic to /usr/local/lib/sinsy/dic.

You can do it on Google colaboratory like this;

  ! mkdir -p /usr/local/lib/sinsy
  ! ln -s /usr/lib/sinsy/dic /usr/local/lib/sinsy/dic

Or you can fix line 66 of egs/pjs/00-svs-world/utils/data_prep.py manually.

Yuuri Natsume's singing voice database has some labeling issues such as differences between scores and original lab files, the difference of time unit and so on. The recipe of natsume_singing has some specialized codes to fix them, and it won't be work with PJS corpus.

**Comment by r9y9** [comment]
Closing due to inactivity
