### ISSUE TITLE
ModuleNotFoundError("No module named 'nnsvs.transformer'")

### ISSUE THREAD

**Issue by talhadar90** [r9y9/nnsvs#199]
I am trying nnsvs streamlit app, im getting this error - I am running on mac. I have installed all the dependencies

2024-02-21 17:04:17.207 Uncaught app exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hydra/_internal/utils.py", line 644, in _locate
    obj = getattr(obj, part)
          ^^^^^^^^^^^^^^^^^^
AttributeError: module 'nnsvs' has no attribute 'model'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hydra/_internal/utils.py", line 650, in _locate
    obj = import_module(mod)
          ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/talha/Documents/upwork/Richard_deCosta/nnsvs/nnsvs/model.py", line 10, in <module>
    from nnsvs.transformer.attentions import sequence_mask
ModuleNotFoundError: No module named 'nnsvs.transformer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/hydra/_internal/utils.py", line 653, in _locate
    raise ImportError(
ImportError: Error loading 'nnsvs.model.MDN':
ModuleNotFoundError("No module named 'nnsvs.transformer'")
Are you sure that 'model' is importable from module 'nnsvs'?

hydra.errors.InstantiationException: Error locating target 'nnsvs.model.MDN', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: netG

**Comment by talhadar90** [comment]
Never mind. I somehow downloaded the source code which did not had transformers in it. 

I redownloaded the git. Now its working.

Can you share a guide to install a new model? I saw the english support model but cant seem to see a installation guide

**Comment by SubrahmanyamNaidu** [comment]
Bro, Can you explain how this model works means,
 I want to know how the data is flowing in the training phase and how I have to prepare my data to train the model. and I have a doubt that is this model can work for the custom language?.
