### ISSUE TITLE
Cannot generate KIRITAN labels

### ISSUE THREAD

**Issue by usasho** [r9y9/nnsvs#4]
musicxml/01.xml
musicxml/02.xml
[WARN] The last note is not rest
[WARN] The last note is not rest
musicxml/03.xml
musicxml/04.xml
musicxml/05.xml
Traceback (most recent call last):
  File "perf_segmentation.py", line 84, in <module>
    np.min(flatten_lengths), np.max(flatten_lengths), np.mean(flatten_lengths)))
  File "<__array_function__ internals>", line 6, in amin
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 2793, in amin
    keepdims=keepdims, initial=initial, where=where)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
Prepare data for time-lag models
  0%|                                                     | 0/5 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "finalize_lab.py", line 49, in <module>
    lab_align = trim_sil_and_pau(hts.load(lab_align_path))
  File "/usr/local/lib/python3.6/dist-packages/nnmnkwii-0.0.21+1cfaeca-py3.6-linux-x86_64.egg/nnmnkwii/io/hts.py", line 325, in load
    return labels.load(path, lines)
  File "/usr/local/lib/python3.6/dist-packages/nnmnkwii-0.0.21+1cfaeca-py3.6-linux-x86_64.egg/nnmnkwii/io/hts.py", line 198, in load
    with open(path) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'kiritan_singing_extra/full_dtw/01.lab'

**Comment by r9y9** [comment]
- Please write the issue description in English so non-Japanese people (> 90% of watchers I believe) can understand and may help
- Based on your provided information, It is too hard to isolate what the problem was. No one won't help you unless if you don't provide sufficient details and the results of your investigation. Please spend your time reading the error messages, and do investigate yourself first.
- If you want to reach me out in Japanese, email me.
