### ISSUE TITLE
Could not finish step 0 on macOS

### ISSUE THREAD

**Issue by sdercolin** [r9y9/nnsvs#48]
Hello, I am facing an issue when trying to run recipes on my local device (macOS):

```
(nnsvs-dev) XXXXX:svs-world-conv sdercolin$ bash run.sh --stage 0 --stop-stage 0
stage 0: Data preparation
Convert musicxml to label files.
100%|███████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:01<00:00, 46.24it/s]
Copy original label files.
100%|██████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 923.08it/s]
Round label files.
100%|█████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 1006.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 541.17it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████| 51/51 [00:00<00:00, 745.91it/s]
0it [00:00, ?it/s]end_time 65050000 of the phoneme ch and start_time 66900000 of the phoneme u is not the same. There seems to be a missing phoneme in sinsy_mono_round.
end_time 68750000 of the phoneme u and start_time 66900000 of the phoneme u is not the same. There seems to be a missing phoneme in sinsy_mono_round.
0it [00:02, ?it/s]
Traceback (most recent call last):
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/align_lab.py", line 57, in <module>
    lab_sinsy = fix_mono_lab_after_align(lab_sinsy, config["spk"])
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/util.py", line 213, in fix_mono_lab_after_align
    return _fix_mono_lab_after_align_natsume_singing(lab)
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/util.py", line 241, in _fix_mono_lab_after_align_natsume_singing
    f.append((f.end_times[-1], lab.end_times[i], lab.contexts[i]))
  File "/Users/sdercolin/dev/nnsvs-dev/lib/python3.8/site-packages/nnmnkwii/io/hts.py", line 159, in append
    raise ValueError(
ValueError: end_time (68750000) must be larger than start_time (68750000).
51it [00:00, 435.75it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/perf_segmentation.py", line 50, in <module>
    base_segments, start_indices, end_indices = segment_labels(
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/util.py", line 117, in segment_labels
    seg.append((s, e, l), strict)
  File "/Users/sdercolin/dev/nnsvs-dev/lib/python3.8/site-packages/nnmnkwii/io/hts.py", line 159, in append
    raise ValueError(
ValueError: end_time (68750000) must be larger than start_time (68750000).
Prepare data for time-lag models
  0%|                                                                                                | 0/51 [00:00<?, ?it/s]1: Global offset (in sec): -0.04
1_seg0.lab offset (in sec): -0.034999999999999996
1.lab: 1/64 time-lags are excluded.
1_seg1.lab offset (in sec): -0.034999999999999996
1.lab: 5/115 time-lags are excluded.
1_seg2.lab offset (in sec): -0.049999999999999996
1_seg3.lab offset (in sec): -0.245
1.lab: 5/11 time-lags are excluded.
1_seg4.lab offset (in sec): -0.034999999999999996
1.lab: 5/114 time-lags are excluded.
1_seg5.lab offset (in sec): -0.06
1.lab: 1/54 time-lags are excluded.
1_seg6.lab offset (in sec): -0.06999999999999999
1_seg7.lab offset (in sec): -0.045
1.lab: 3/49 time-lags are excluded.
1_seg8.lab offset (in sec): -0.06
1.lab: 4/66 time-lags are excluded.
10: Global offset (in sec): -0.055
10_seg0.lab offset (in sec): -0.08499999999999999
10_seg1.lab offset (in sec): -0.095
10.lab: 1/11 time-lags are excluded.
10_seg2.lab offset (in sec): -0.095
10.lab: 5/27 time-lags are excluded.
10_seg3.lab offset (in sec): -0.075
10.lab: 1/11 time-lags are excluded.
10_seg4.lab offset (in sec): -0.13999999999999999
10.lab: 1/10 time-lags are excluded.
10_seg5.lab offset (in sec): -0.075
10.lab: 2/15 time-lags are excluded.
10_seg6.lab offset (in sec): -0.09
10.lab: 3/10 time-lags are excluded.
10_seg7.lab offset (in sec): -0.13999999999999999
10.lab: 2/10 time-lags are excluded.
10_seg8.lab offset (in sec): -0.11
10.lab: 3/10 time-lags are excluded.
10_seg9.lab offset (in sec): -0.06999999999999999
10.lab: 3/15 time-lags are excluded.
10_seg10.lab offset (in sec): -0.38999999999999996
10.lab: 9/10 time-lags are excluded.
11: Global offset (in sec): -2.17
11_seg0.lab offset (in sec): -2.17
11.lab: 6/39 time-lags are excluded.
12: Global offset (in sec): -3.8249999999999997
  6%|█████▏                                                                                  | 3/51 [00:00<00:01, 32.91it/s]
Traceback (most recent call last):
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/finalize_lab.py", line 89, in <module>
    assert seg_idx > 0 or exists(lab_align_path)
AssertionError
(nnsvs-dev) XXXXX:svs-world-conv sdercolin$
```

Some information:
1. The above is the result for recipe `natsume_singing`, but the similar errors also occur when I tried another recipe `ofuton_p_utagoe_db`.
2. I have succeed with everything on colab (https://colab.research.google.com/gist/taroushirani/3e54d01e9e85674dbb8eaa7e0e457acd/nnsvs_ofuton_p_utagoe_db_official_recipe.ipynb), and followed the same installation steps on macOS, except:
  - Installed everything in `/usr/local/` instead of `/usr/`
  - Using python virtual env
  - **Probably important**: Did `export ARCHFLAGS="-arch x86_64"` before installing `pysinsy`, because without that I get a lot of `unknown type name '__int64_t'`. Ref: https://github.com/giampaolo/psutil/issues/1832#issuecomment-704596756

My Environment:
- OS: macOS Catalina 10.15.7 (Intel)
- Python: 3.8.2

Thanks in advance!

**Comment by sdercolin** [comment]
Logs for recipe `ofuton_p_utagoe_db`
```
(nnsvs-dev) XXXXX:svs-world-conv sdercolin$ bash run.sh --stage 0 --stop-stage 0
stage 0: Data preparation
Convert musicxml to label files.
100%|███████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 57.12it/s]
Copy original label files.
100%|█████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 1191.23it/s]
Round label files.
100%|█████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 1269.17it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 1013.24it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████| 57/57 [00:00<00:00, 1227.34it/s]
0it [00:00, ?it/s]akai_kutsu.lab 0.0
akatombo.lab 0.0
2it [00:00, 13.61it/s]amefuri.lab 0.0
antagata_dokosa.lab 0.0
4it [00:00, 11.71it/s]aogeba_tootoshi.lab 0.0
arupusu_itimanjaku.lab 0.0
6it [00:00,  7.72it/s]chatsumi.lab 1.0
chouchou.lab 0.0
8it [00:00,  8.35it/s]daikokusama.lab 0.0
9it [00:01,  7.63it/s]donguri_korokoro.lab 0.0
furusato.lab 0.0
11it [00:01,  8.10it/s]genkotsuyamano_tanukisan.lab 0.0
haruga_kita.lab 0.0
haruno_ogawa.lab 0.0
14it [00:01, 10.09it/s]haruyo_koi.lab 0.0
hato.lab 0.0
16it [00:01, 11.80it/s]hato_low.lab 0.0
hiraita_hiraita.lab 0.0
18it [00:01, 12.95it/s]hotaruno_hikari.lab 0.0
issunboushi.lab 0.0
20it [00:02,  9.76it/s]kagome_kagome.lab 0.0
kagome_kagome_low.lab 0.0
kamomeno_suiheisan.lab 0.0
23it [00:02, 11.02it/s]katatsumuri.lab 0.0
kintaro.lab 0.0
25it [00:02, 12.03it/s]koganemushi.lab 0.0
koinobori.lab 0.0
momiji.lab 0.0
28it [00:02, 12.11it/s]momotarou.lab 0.0
morobito_kozorite.lab 0.0
30it [00:02,  9.39it/s]mushino_koe.lab 0.0
my_grandfathers_clock_1_1.lab 0.0
32it [00:03,  8.73it/s]my_grandfathers_clock_1_2.lab 0.0
my_grandfathers_clock_1_3.lab 0.0
34it [00:03,  8.82it/s]my_grandfathers_clock_2_1.lab 0.0
my_grandfathers_clock_2_2.lab 0.0
36it [00:03,  9.29it/s]my_grandfathers_clock_2_3.lab 0.0
37it [00:03,  9.24it/s]my_grandfathers_clock_3_1.lab 0.0
38it [00:03,  9.24it/s]my_grandfathers_clock_3_2.lab 0.0
39it [00:04,  9.04it/s]my_grandfathers_clock_3_3.lab 0.0
40it [00:04,  8.76it/s]nanatsunoko.lab 0.0
oborodukiyo.lab 0.0
42it [00:04,  9.44it/s]sakura_sakura.lab 0.0
seikurabe.lab 0.0
44it [00:04,  8.59it/s]shabondama.lab 0.0
shoujoujino_tanukibayashi.lab 0.0
46it [00:04,  9.24it/s]tetsudou_shouka.lab 0.0
47it [00:04,  8.33it/s]tombi.lab 0.0
48it [00:05,  8.55it/s]tooryanse.lab 0.0
urashima_taro.lab 0.0
50it [00:05,  8.19it/s]usagi.lab 0.0
usagito_kame.lab 0.0
52it [00:05,  9.22it/s]warewa_uminoko.lab 0.0
53it [00:05,  8.16it/s]yuki.lab 0.0
54it [00:05,  8.50it/s]yurikagono_uta.lab 0.0
zuizuizukkorobashi.lab 0.0
56it [00:05, 10.06it/s]zuizuizukkorobashi_low.lab 0.0
57it [00:05,  9.54it/s]
57it [00:00, 697.88it/s]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/perf_segmentation.py", line 50, in <module>
    base_segments, start_indices, end_indices = segment_labels(
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/util.py", line 117, in segment_labels
    seg.append((s, e, l), strict)
  File "/Users/sdercolin/dev/nnsvs-dev/lib/python3.8/site-packages/nnmnkwii/io/hts.py", line 163, in append
    raise ValueError(
ValueError: start_time (197850000) must be equal to the last end_time (191750000).
Prepare data for time-lag models
  0%|                                                                                                | 0/57 [00:00<?, ?it/s]akai_kutsu: Global offset (in sec): -0.024999999999999998
  0%|                                                                                                | 0/57 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/sdercolin/dev/nnsvs-dev/nnsvs/egs/_common/no2/utils/finalize_lab.py", line 89, in <module>
    assert seg_idx > 0 or exists(lab_align_path)
AssertionError
```

**Comment by taroushirani** [comment]
Hello.  This looks like fastdtw-related problem for me.

The recipes of ofuton_p_utagoe_db, natsume_singing, oniku_kurumi_utagoe_db make use of fastdtw to guarantee the consistency between mono-phone label files included in singing voice databases and full-context label files converted from musicxml.   There are two implementation of fastdtw, c++ version and pure python version, and their output differs with a specific input.

For detail, please see https://github.com/slaypni/fastdtw/issues/46.

**Comment by taroushirani** [comment]
Please try the following code.
```
import numpy as np
from fastdtw import fastdtw

x = [1, 6, 6, 33, 35]
y = [1, 6, 6, 33, 35]

d, path = fastdtw(x, y, radius=len(x))

print(f"d: {d}")
print(f"path: {path}")
```
The output of pure python version will be:
```
d: 0.0
path: [(0, 0), (1, 1), (1, 2), (2, 2), (3, 3), (4, 4)]
```
The output of c++ version will be:
```
d: 0.0
path: [(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]
```
If you installed fastdtw with pip, installation from source may help you.

**Comment by sdercolin** [comment]
I tried to build fastdtw from source code, even edited `setup.py` to ensure Cython is used, but the result still contains `(1,2)`.
Finally I changed my Python to `3.7.3`, and reinstalled everything, and it works.... don't know why though..
Thanks for your help!!

**Comment by smlim01** [comment]
I had same error, and I solved this error using past version of fastdtw.
`pip install fastdtw==0.3.2`

**Comment by hilmiyafia** [comment]
I have the same issue, installing from source, downgrading to 3.7.3, using fastdtw 0.3.2, none of them work for me. Please help.

**Comment by taroushirani** [comment]
I think there is something wrong with the compilation from the source cde.   Could you please execute the following commands and paste the content of build.log here?

    git clone https://github.com/slaypni/fastdtw.git
    cd fastdtw && python setup.py build --verbose  > build.log 2>&1

The other day I met this problem too.  "tp_print" is removed from python 3.9 and re-cythonizing was needed at that time.

**Comment by hilmiyafia** [comment]
@taroushirani Okay! It works now! Thank you very much! 😊
